### ISSUE TITLE
I want to only check the apple-app-site-association file but it needs an ipa file

### ISSUE THREAD

**Issue by gensmusic** [shortstuffsushi/Universal-Link-Validator#2]
Can I check the file only without commit a .ipa file ?

**Comment by shortstuffsushi** [comment]
Do you have another format in mind? I believe IPA files are they only ones with the resources included, though it's possible that APP files do as well (the file exported by your typical build and installed on the simulator). XCArchives likely do as well.

What are you concerns about the IPA?

**Comment by gensmusic** [comment]
My apple ID is group ID and I don't have the permission to archive to get the ipa files.

**Comment by shortstuffsushi** [comment]
Alright, what file are you able to get? I may or may not be able to use it -- I need to be able to look at the entitlements file, and I'm not sure offhand which file types that gets bundled with.

**Comment by gensmusic** [comment]
I have all the source code. I just can't archive it to ipa file.

**Comment by shortstuffsushi** [comment]
Ok, well there are a few things you can check, if you can't upload a packaged file.
- You need to add the domain in the Capabilities tab
- You need to have it in you Member Center on the Apple developer site
- You should add the continueUserActivity code in your AppDelegate

If you're able to build _anything_, and can send me some artifact (say, a .app or .xcarchive), I can take a look and see if there is something I can add the the validator about it.

**Comment by shortstuffsushi** [comment]
Re-open if you feel there is anything my tool can provide to assist this.
