### ISSUE TITLE
Update to accept unsigned files

### ISSUE THREAD

**Issue by jsorge** [shortstuffsushi/Universal-Link-Validator#3]
According to the WWDC session video here: https://developer.apple.com/videos/play/wwdc2015-509/?time=846, the JSON file doesn't need to be SSL signed as of seed 2 of iOS 9. How difficult would it be to update the tool to support unsigned files?

**Comment by shortstuffsushi** [comment]
It wouldn't be difficult, but from what I've seen so far, this isn't the case, and the signing is still required. I did see them say that as well, but at least up to 9.1, this wasn't the case.

**Comment by shortstuffsushi** [comment]
Merged into master :+1:

**Comment by ghost** [comment]
The note from the [Creating and Uploading the Association File](https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/AppSearch/UniversalLinks.html#//apple_ref/doc/uid/TP40016308-CH12-SW2) doc suggested unencrypted is fine if served via HTTPS to iOS 9+ clients as `application/json`:

> **NOTE**
> If your app runs in iOS 9 or later and you use HTTPS to serve the `apple-app-site-association` file, you can create a plain text file that uses the `application/json` MIME type and you don’t need to sign it. If you use HTTP to serve the `apple-app-site-association` file, or you support Handoff and Shared Web Credentials in iOS 8, you still need to sign the file as described in [Shared Web Credentials Reference](https://developer.apple.com/library/prerelease/ios/documentation/Security/Reference/SharedWebCredentialsRef/index.html#//apple_ref/doc/uid/TP40014989).

**Comment by shortstuffsushi** [comment]
From the page you linked, there was a revision October 21st:

`Updated information about the signing requirements for the apple-app-site-association file.`

It's possible they've finally removed this as a requirement. I'm not going to test this out immediately, but you're welcome to test and see if just an unsigned file with the Content-Type set to `application/json` actually works for universal linking on a device. At that point, there isn't a _huge_ need for this tool, as the signing piece was what I always found to be the biggest hangup.

However, I still find it valuable for the end-to-end test -- drop in an IPA, validate that it has the Associated Domains, the sites in that list have the file, and have identifiers _matching_ the actual app bundle identifier. It's easy to miss a step along the way, and having a tool to check is still useful, imo.

For what it's worth, I actually [am allowing `application/json`](https://github.com/shortstuffsushi/Universal-Link-Validator/blob/6ae4d8bb72aac1af98d99f0b28961e5621e9fa31/checkDomain.js#L171) as a valid type, when you've specified the "allow unencrypted" flag.

**Comment by ghost** [comment]
Excellent, it sounds as though the tool already supports the change then! I'll give the unsigned file route a try early next week and report back my findings.

**Comment by shortstuffsushi** [comment]
Sounds great, looking forward to hearing how that goes. That would certainly make things easier for a lot of devs, or at least those who no longer need to support iOS 8.

**Comment by ponchorage** [comment]
I've tried it and have been unable to get it to work, but that's been both signed and unsigned. Apple's verification tool seems to think everything is fine. I've never tried uploading an IPA to verify so maybe I'll give that a shot. I think it may have something to do with our certificate but I can't be sure. It's a wildcard cert.

**Comment by ponchorage** [comment]
I just tried the IPA and got an error. What does this mean?
```
Must be able to find entitlements (looking in My App/Payload/My App.app/archived-expanded-entitlements.xcent)
```

**Comment by shortstuffsushi** [comment]
I don't believe certs are actually validated by my tool, it just verifies that the openssl utility is able to "un-smime" it. What specific errors are you seeing? Feel free to shoot me an email directly if it's easier.

**Comment by shortstuffsushi** [comment]
I believe you may have had a separate comment on here asking about an issue with the IPA, and what the path thing meant. Basically, the ULV takes the IPA, treats it like a zip and unzips it. It has certain expectations about the structure of the result, specifically that it's (off the top of my head) `/AppName/Payload/AppName.app`, and within that, it searches for a couple of files, including the entitlements file. When compiled, the entitlements file is renamed to `archived-expanded-entitlements.xcent`, and if it is unable to find or open that, it assumes there is an issue with your project.

If you're still seeing issues with that, feel free to unzip an IPA locally and check your contents. If you're seeing the expected structure, and the ULV is failing to parse that correctly, feel free to open another issue with information about that.

**Comment by ghost** [comment]
In a quick test, the AASA file does **not** need to be signed if served as `application/json` and is otherwise flagged as valid when the _Allow unencrypted AASA files_ checkbox is enabled.

**Comment by shortstuffsushi** [comment]
Sorry @pizthewiz, not entirely understanding you. It sounds like you're saying things are working. Right?

If the file is not signed AND
The file is application/json AND
The allow unencrypted is checked

Then it's flagged valid?

That seems correct to me. Is that what you're describing?

**Comment by ghost** [comment]
Correct, the AASA file is not signed, is served as `application/json` and in the validator the _Allow unencrypted…_ is checked - the validator then flags it as legal and sure enough, testing it on device works as well.

**Comment by shortstuffsushi** [comment]
Ah, well great then, glad it's working. I haven't actually tested that an unsigned file works for UL yet, though it did seem that the requirement for signing may have been removed with 8.1
