### ISSUE TITLE
Validate Bundle ID

### ISSUE THREAD

**Issue by Skornos** [shortstuffsushi/Universal-Link-Validator#4]
Hi,

thanks for this great resource, it helped me a lot. However now I have spent 2 hours trying to find why my Universal links aren't working when all the tests in the validator passed and it turned out I have misspelled Bundle ID. Would it be possible to check this in the future so it would prevent other people from spending their time on similar issue?

Thanks.

**Comment by shortstuffsushi** [comment]
This and other JSON validation improvements are on the way :smile:

**Comment by shortstuffsushi** [comment]
Merged into master :+1:

**Comment by Skornos** [comment]
thanks :)
