### ISSUE TITLE
Getting json invalid message

### ISSUE THREAD

**Issue by ponchorage** [shortstuffsushi/Universal-Link-Validator#5]
I'm pretty sure my json is valid but I'm getting the message telling me:

This domain AASA was pulled, but the JSON format is Invalid

The domain I'm testing is ksl.com. I've checked the checkmark to "Allow unencrypted AASA files".

**Comment by nikhilcognizant** [comment]
Same here. Twitter.com JSON invalid

**Comment by shortstuffsushi** [comment]
This was a mistake on the type check on my end. I've committed the fix for this, but won't be able to deploy until later this evening.

**Comment by shortstuffsushi** [comment]
Deployed now :+1:
