### ISSUE TITLE
If apple-app-site-association is in .well-known/, validator responds with "Your server shouldn't return an error status code (>= 400)"

### ISSUE THREAD

**Issue by markymc** [shortstuffsushi/Universal-Link-Validator#7]
First off - Thanks for creating this! :)

As per title, shouldn't this check in .well-known/ if the root returns a 404? Apple states that we can place it in either the root or .well-known/ Or am I missing something?

**Comment by shortstuffsushi** [comment]
Hi Mark,

Thanks for pointing this out. I haven't been keeping up with all the
changes, as I haven't been going much iOS dev for a while now. I will look
into this when I have a chance, or feel free to submit a PR.

**Comment by markymc** [comment]
Thanks for the quick reply, @shortstuffsushi! Unfortunately I'm not a Node/JS guy, so not sure if I could be any help with a PR. :) I've pinged the guys at Branch.io (https://branch.io/resources/universal-links/) about it too, so perhaps they'd be able to help as it's a problem for them too.

**Comment by shortstuffsushi** [comment]
Hi @markymc, I've implemented this now. Check it out, and let me know if it works for you.
